name: CI

on:
  push:
    branches: [ main ]

jobs:
  dev-deploy:
    name: Building Dev image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dev image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: felipehimself/mfe-navbar:dev

  prod-deploy:
    name: Building Prod image
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
      - name: Request Approval
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue = await github.issues.create({
              owner,
              repo,
              title: 'Requesting Deployment Approval to Production',
              body: 'A new build is ready for deployment to production. Please review and approve the deployment.'
            });
            core.setOutput('issue_number', issue.data.number);

      - name: Wait for Approval
        id: approval
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = core.getInput('issue_number');
            let approved = false;

            // Poll for approval
            while (!approved) {
              const { data: comments } = await github.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
              });

              if (comments.some(comment => comment.body === '/approve')) {
                approved = true;
              } else {
                console.log('Waiting for approval...');
                await new Promise(resolve => setTimeout(resolve, 60000)); // Wait 1 minute
              }
            }

      - name: Checkout
        if: steps.approval.outputs.approved == 'true'
        uses: actions/checkout@v2

      - name: Buildx
        if: steps.approval.outputs.approved == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub login
        if: steps.approval.outputs.approved == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push prod image
        if: steps.approval.outputs.approved == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: felipehimself/mfe-navbar:latest